version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  dev_server:
    build: .
    working_dir: /varys/frontend
    command: bash -c "yarn install --production=false && yarn start"
    volumes:
      - ~/.aws:/root/.aws
      - ~/.aws:/.aws
      - ./deploy_keys:/root/.ssh
      - ./:/varys
      - ./.irbrc:/root/.irbrc
    environment:
      - DEV_SERVER_PROXY=http://varys:3000
    ports:
      - "8000:8000"
    depends_on:
      - varys
  varys:
    build: .
    command: bundle exec unicorn_rails -c config/unicorn.rb
    volumes:
      - ~/.aws:/root/.aws
      - ~/.aws:/.aws
      - ./deploy_keys:/root/.ssh
      - ./:/varys
      - ./.irbrc:/root/.irbrc
    ports:
      - "3000:3000"
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENVIRONMENT=development
      - VARYS_DATABASE_PASSWORD=root
      - VARYS_DATABASE_USER=root
      - VARYS_DATABASE_HOST=db
      - USER=${USER}
      - VARYS_STAGE=local
      - VARYS_REDIS_URL=redis
      - VARYS_REDIS_PORT=6379
      - UNICORN_CWD=/varys
      - SECRET_KEY_BASE=ba97723a703ca6aeeb1eef8ec869102134ca81f0d7e50271c8672161551ceb82931e68e71cad7bfdc8a62d37e4414aea04dc529df8fc9711ee5d2302d3ed2e43
      - PAPERCLIP_HASH_SECRET=3cfc4f8be8a7bcf26c4e38932664891c349eebfa1fc341e061fdfabdd11fc035325d5f7b4ec51cee6776cb867859d0913452beb1d653190891fe3765d76adb99
      - ELASTICSEARCH_URL=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - S3_ACCESS_KEY_ID=dummy
      - S3_SECRET_ACCESS_KEY=dummy
      - REGIONAL_PROXY_USER=dummy
      - REGIONAL_PROXY_PASSWORD=dummy
      - RECAPTCHA_SITE_KEY=dummy
      - RECAPTCHA_SECRET_KEY=dummy
      - CLEARBIT_KEY=dummy
      - MIGHTYBIT_API_TOKEN=dummy
      - REDSHIFT_DATABASE_USER=root
      - REDSHIFT_DATABASE_PASSWORD=root
      - REDSHIFT_DATABASE_HOST=redshift
      - REDSHIFT_DATABASE_PORT=5432
      - SCREENSHOTLAYER_ACCESS_KEY=nop
      - SCREENSHOTLAYER_SECRET_KEYWORD=nop
      - HOT_STORE_REDIS_URL=redis
      - HOT_STORE_REDIS_PORT=6379
      - HOT_STORE_REDIS_MAX_CONNECTIONS=6
    depends_on:
      - db
      - redis
      - elasticsearch
      - proxy
      - redshift
  redis:
    image: redis:2.8
    expose:
      - "6379"
  nginx:
    build: .
    ports:
      - "8888:80"
    command: nginx -g "daemon off;"
    volumes:
      - ./container_assets/sites-available:/etc/nginx/sites-available/default
    depends_on:
      - varys
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - ~/.aws:/root/.aws
      - ~/.aws:/.aws
      - ./:/varys
    environment:
      - RAILS_ENVIRONMENT=development
      - VARYS_DATABASE_PASSWORD=root
      - VARYS_DATABASE_USER=root
      - VARYS_DATABASE_HOST=db
      - USER=${USER}
      - VARYS_STAGE=local
      - VARYS_REDIS_URL=redis
      - VARYS_REDIS_PORT=6379
      - SECRET_KEY_BASE=ba97723a703ca6aeeb1eef8ec869102134ca81f0d7e50271c8672161551ceb82931e68e71cad7bfdc8a62d37e4414aea04dc529df8fc9711ee5d2302d3ed2e43
      - PAPERCLIP_HASH_SECRET=3cfc4f8be8a7bcf26c4e38932664891c349eebfa1fc341e061fdfabdd11fc035325d5f7b4ec51cee6776cb867859d0913452beb1d653190891fe3765d76adb99
      - SIDEKIQ_QUEUES=noop
      - SIDEKIQ_CONCURRENCY=1
      - ELASTICSEARCH_URL=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - S3_ACCESS_KEY_ID=dummy
      - S3_SECRET_ACCESS_KEY=dummy
      - REGIONAL_PROXY_USER=dummy
      - REGIONAL_PROXY_PASSWORD=dummy
      - RECAPTCHA_SITE_KEY=dummy
      - RECAPTCHA_SECRET_KEY=dummy
      - REDSHIFT_DATABASE_USER=root
      - REDSHIFT_DATABASE_PASSWORD=root
      - REDSHIFT_DATABASE_HOST=redshift
      - REDSHIFT_DATABASE_PORT=5432
      - HOT_STORE_REDIS_URL=redis
      - HOT_STORE_REDIS_PORT=6379
      - HOT_STORE_REDIS_MAX_CONNECTIONS=6
    depends_on:
      - db
      - redis
      - elasticsearch
      - proxy
      - redshift
  elasticsearch:
    image: elasticsearch:2.3
    ports:
      - "9200:9200"
  proxy:
    image: 250424072945.dkr.ecr.us-east-1.amazonaws.com/squid:latest
  redshift:
    image: postgres:9.6 # just use any postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=data
    ports:
      - "5439:5432"
