version: 2
jobs:
    test:
        docker:
            - image: circleci/python:2.7
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout
            - run:
                name: Install AWS CLI
                command: sudo pip install awscli
            - run:
                name: Login to ECR
                command: $(aws ecr get-login --no-include-email --region us-east-1)
            - run:
                name: Build Docker images
                command: docker-compose -f circleci-compose.yml build
            - run:
                name: Run tests
                command: docker-compose -f circleci-compose.yml run varys bash -c "sleep 5 && rake db:create db:schema:load test"
    build:
        docker:
            - image: circleci/python:2.7
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout
            - run:
                name: Install AWS CLI
                command: sudo pip install awscli
            - run:
                name: Login to ECR
                command: $(aws ecr get-login --no-include-email --region us-east-1)
            - run:
                name: Build Docker image
                command: docker build -t varys:$CIRCLE_TAG --build-arg bundle_mode='--deployment' --build-arg exclude_gems='development test' .
            - run: docker tag varys:$CIRCLE_TAG 250424072945.dkr.ecr.us-east-1.amazonaws.com/varys:$CIRCLE_TAG.rc
            - run: docker push 250424072945.dkr.ecr.us-east-1.amazonaws.com/varys:$CIRCLE_TAG.rc
    deploy:
        environment:
            AWS_DEFAULT_REGION: "us-east-1"
        docker:
            - image: circleci/python:2.7
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout
            - run:
                name: Install AWS CLI
                command: sudo pip install awscli
            - run:
                name: Login to ECR
                command: $(aws ecr get-login --no-include-email --region us-east-1)
            - run:
                name: Retag image in ECR
                command: |
                        MANIFEST=$(aws ecr batch-get-image --repository-name varys --image-ids imageTag=$CIRCLE_TAG.rc --query images[].imageManifest --output text)
                        aws ecr put-image --repository-name varys --image-tag $CIRCLE_TAG --image-manifest "$MANIFEST"
            - run: aws ecr describe-images --repository-name varys --image-ids imageTag=$CIRCLE_TAG
            - run: bin/notify_build.py

workflows:
    version: 2
    build_test_deploy:
        jobs:
            - test:
                filters:
                    tags:
                        only: /.*/
            - build:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
            - deploy:
                filters:
                    tags:
                        only: /.*/
                    branches:
                        ignore: /.*/
                requires:
                    - build
                    - test
