machine:
  pre:
    - rm varys/.ruby-version
  ruby:
    version: 2.4.1
  services:
    - redis
    - docker
  environment:
    VARYS_REDIS_URL: localhost
    VARYS_REDIS_PORT: 6379
dependencies:
  pre:
    - $(aws ecr get-login --region us-east-1)
    - gem install bundle && bundle config path ~/bundle/
  cache_directories:
    - "~/bundle"
compile:
  override:
    - echo 'Override automatic middleman compilation'
test:
  override:
    - bundle exec rubocop
    - bundle exec rake test
deployment:
  release:
    tag: /.*/
    commands:
      - git reset --hard && git clean -d -x -f && rm .ruby-version
      - export CIRCLE_BRANCH=`echo $CIRCLE_TAG | awk -F '.' '{print $1}'` && ./docker-cache-shim pull 250424072945.dkr.ecr.us-east-1.amazonaws.com/varys
      - docker build -t varys --build-arg bundle_mode='--deployment' --build-arg exclude_gems='development test' .
      - docker tag varys:latest 250424072945.dkr.ecr.us-east-1.amazonaws.com/varys:$CIRCLE_TAG
      - docker push 250424072945.dkr.ecr.us-east-1.amazonaws.com/varys:$CIRCLE_TAG
      - export CIRCLE_BRANCH=`echo $CIRCLE_TAG | awk -F '.' '{print $1}'` && ./docker-cache-shim push 250424072945.dkr.ecr.us-east-1.amazonaws.com/varys:$CIRCLE_TAG
      - bin/notify_build.rb
