service: device-lab-monitor


provider:
  name: aws
  runtime: python2.7
  stage: production
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:*
      Resource: "arn:aws:sns:us-east-1:250424072945:device_lab_alarms"

functions:
  alerts:
    handler: handler.handle_device_event
    events:
      - sns: arn:aws:sns:us-east-1:250424072945:device_lab_alarms
    environment:
      DASHBOARD_HOST: ${env:DASHBOARD_HOST}
      VARYS_API_ENDPOINT: ${env:VARYS_API_ENDPOINT}
      VARYS_SECRET: ${env:VARYS_SECRET}