# config/chewy.yml
# separate environment configs
default: &default
  host: "<%= ENV['ELASTICSEARCH_URL'] %>:<%= ENV['ELASTICSEARCH_PORT'] %>"
development:
  <<: *default
  user: <%= ENV['ELASTICSEARCH_USER'] %>
  password: <%= ENV['ELASTICSEARCH_PASSWORD'] %>
test:
  <<: *default
  prefix: 'test'
production:
  <<: *default
  user: <%= ENV['ELASTICSEARCH_USER'] %>
  password: <%= ENV['ELASTICSEARCH_PASSWORD'] %>
