# config/chewy.yml
# separate environment configs
test:
  host: 'localhost:9250'
  prefix: 'test'
development:
  host: 'localhost:9200'
production:
  host: 'http://57ee73786e08205571d6e29709308c9c.us-east-1.aws.found.io:9200'