:queues:
<% (ENV['SIDEKIQ_QUEUES'] || 'noop').split(',').each do |queue| %>
  - <%= queue %>
<% end %>
:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 1 %>
:logfile: /tmp/sidekiq.log
:pidfile: /tmp/sidekiq.pid
:timeout: 20
