class FastestGrowingSdksController < ApplicationController
  include ApiHelper
  skip_before_filter  :verify_authenticity_token

  def top_install_base
    # File generated by FastestGrowingSdkReportGenerator.
    data = Rails.cache.fetch('fastest_growing_sdk_report_2017.json.gz', expires: 30.days, compress: true) do
       MightyAws::S3.new.retrieve(
        bucket: 'mightysignal-sdk-install-base-data',
        key_path: 'fastest_growing_sdk_report_2017.json.gz'
      )
    end
    render json: data
  end

  def blog_post_redirect
    redirect_to "https://medium.com/@champagneshane/838657d3457a"
  end

end
