require_relative 'mighty_deployer'

MightyDeployer.test
MightyDeployer.define_web_api_servers
MightyDeployer.define_scraper_servers
MightyDeployer.define_sdk_scraper_servers
MightyDeployer.define_roles